# Generated by Django 5.2 on 2025-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('oddiy', 'Oddiy'), ('diler', 'Diler')], default='oddiy', max_length=5),
        ),
    ]
