# Generated by Django 5.2 on 2025-04-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/images/'),
        ),
    ]
