# Generated by Django 5.2 on 2025-04-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Benzin'), ('diesel', 'Dizel'), ('electric', 'Elektr'), ('hybrid', 'Gibrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Mexanik'), ('automatic', 'Avtomatik'), ('cvt', 'CVT'), ('semi-automatic', 'Yarim avtomatik')], max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('mileage', models.PositiveIntegerField()),
                ('engine_size', models.FloatField()),
                ('power', models.PositiveIntegerField()),
                ('drive_type', models.CharField(choices=[('fwd', 'Old balon'), ('rwd', 'Orqa balon'), ('awd', 'Toliq yuruvchi')], max_length=20)),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.bodytype')),
                ('features', models.ManyToManyField(blank=True, to='vehicles.feature')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.model')),
            ],
        ),
    ]
